spring:
  profiles:
    active: peer1
  application:
    name: @pom.artifactId@
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    peer-eureka-nodes-update-interval-ms: 5000
  instance:
    hostname: peer1
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    appname: muyclound-eureka
    lease-expiration-duration-in-seconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8761