spring:
  profiles:
    active: peer3
  application:
    name: @pom.artifactId@
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    peer-eureka-nodes-update-interval-ms: 5000
  instance:
    hostname: peer3
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    appname: muyclound-eureka
    lease-expiration-duration-in-seconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://root:root@peer1:8761/eureka/,http://root:root@peer2:8762/eureka/
server:
  port: 8763