server:
  tomcat:
    uri-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  application:
    name: @pom.artifactId@
management:
  security:
    enabled: false
info:
  owner: muyclound.net@gmail.com
  version: @project.version@
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    umc-route:
      path: /umc/**
      sensitiveHeaders:
      serviceId: muyclound-provider-umc
      stripPrefix: true
    omc-route:
      path: /omc/**
      sensitiveHeaders:
      serviceId: muyclound-provider-omc
      stripPrefix: true
    b2b-route:
      path: /b2b/**
      sensitiveHeaders:
      serviceId: muyclound-consumer-b2b
      stripPrefix: true
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 60000
muyclound:
  token:
    interceptor:
      enable: true
  oauth2:
    jwtSigningKey: www.muyclound.com
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
  security:
    oauth2:
          tokenStore: jwt
          clients[0]:
            clientId: paascloud-client-umc
            clientSecret: muycloundClientSecret
            accessTokenValidateSeconds: 7200
            scope: "*"
          clients[1]:
            clientId: muyclound-client-gateway
            clientSecret: muycloundClientSecret
            accessTokenValidateSeconds: 7200
            scope: "*"
          clients[2]:
            clientId: muyclound-client-b2b
            clientSecret: muycloundClientSecret
            accessTokenValidateSeconds: 7200
            scope: "*"