spring:
  application:
    name: @pom.artifactId@
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@peer1/eureka/,http://root:root@peer2/eureka/,http://root:root@peer3/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
server:
  port: ${muyclound.server.provider.umc.port:8000}